/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidencryptiondemo_ndk_NdkUtil */

#ifndef _Included_com_example_androidencryptiondemo_ndk_NdkUtil
#define _Included_com_example_androidencryptiondemo_ndk_NdkUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_androidencryptiondemo_ndk_NdkUtil
 * Method:    getRsaPublicKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_androidencryptiondemo_ndk_NdkUtil_getRsaPublicKey
  (JNIEnv *, jobject);

/*
 * Class:     com_example_androidencryptiondemo_ndk_NdkUtil
 * Method:    getRsaPrivateKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_androidencryptiondemo_ndk_NdkUtil_getRsaPrivateKey
  (JNIEnv *, jobject);

/*
 * Class:     com_example_androidencryptiondemo_ndk_NdkUtil
 * Method:    setRsaPublicKey
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_androidencryptiondemo_ndk_NdkUtil_setRsaPublicKey
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
